#!/bin/bash
TERM=dumb
export TERM 

cd /home/barttyra/domains/zjebane.pl/public_html/typer/app/
./cake Odder fetch_events > /home/barttyra/domains/zjebane.pl/public_html/typer/app/tmp/logs/odds_update.log