#!/bin/bash
TERM=dumb
export TERM 

cd /home/barttyra/domains/bartyr.net/public_html/typer/app/
./cake Odder fetch_events >> /home/barttyra/domains/bartyr.net/public_html/typer/app/tmp/logs/odds_update.log